### ISSUE TITLE
Inclusão de Personas no Relatório de Usuabilidade

### ISSUE THREAD

**Issue by juliodex21** [Trabalho-web-mobile/MundoCorpoWeb#4]
Inclui o Relatório de Usabilidade com a tarefa, 2. Perguntas para entrevista/questionário e 2.1. Elaboração de Personas, realizada pela dupla Júlio e Kevin.

[Relatorio de Usabilidade (Personas).docx](https://github.com/Trabalho-web-mobile/MundoCorpoWeb/files/9735219/Relatorio.de.Usabilidade.Personas.docx)

**Comment by gaadriano** [comment]
Fim da issue.
