### ISSUE TITLE
Entrevista com potenciais usuários para avaliar o site

### ISSUE THREAD

**Issue by JuanHenrique04** [Trabalho-web-mobile/MundoCorpoWeb#5]
Segue formulário para realização das entrevistas: [Formulário Modelo SUS (System Usability Scale)](https://docs.google.com/forms/d/e/1FAIpQLSdbdlnTLDHNivQ-Tx88qjF3hWT5Y2aamu3h5QAqCiZIhwPJGQ/viewform?usp=sf_link)

**Comment by JuanHenrique04** [comment]
- Fazer entrevista com potenciais usuários para avaliar o site (mínimo 3 pessoas).

1. Usar as métricas de usabilidade do SUS (System Usability Scale). Modelo de Formulário
2. Mostrar os gráficos com as respostas fechadas.
3. Mostrar as melhorias sugeridas pelos usuários.

**Comment by JuanHenrique04** [comment]
Formulário com visualização de respostas [Form](https://docs.google.com/forms/d/1usIhYYSXPK3hr4eRL2-Lic38tw3XTp5My_PrNmylB28/edit#responses)

**Comment by gaadriano** [comment]
Fim da issue.
